name: test

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build

      - name: start gRPC server
        run: node dist/server.js &

      - name: test
        run: yarn test

      - name: Stop gRPC server
        run: killall node
